server: { port: 9021 }
spring:
  application: { name: swaps-service }
  datasource:
    url: jdbc:postgresql://localhost:5434/swaps
    username: swaps
    password: swaps
  jpa.hibernate.ddl-auto: validate
  flyway.enabled: true
eureka.client.service-url.defaultZone: http://localhost:8761/eureka
