version: "3.9"

networks:
  ats-net:

volumes:
  pgdata-auth:
  pgdata-swaps:

services:
  postgres-auth:
    image: postgres:16
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -d auth"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [ats-net]

  postgres-swaps:
    image: postgres:16
    environment:
      POSTGRES_USER: swaps
      POSTGRES_PASSWORD: swaps
      POSTGRES_DB: swaps
    ports:
      - "5434:5432"
    volumes:
      - pgdata-swaps:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swaps -d swaps"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [ats-net]

  config-server:
    build:
      context: ./platform/config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks: [ats-net]

  discovery-server:
    build:
      context: ./platform/discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      config-server:
        condition: service_started
    networks: [ats-net]

  auth-service:
    build:
      context: ./platform/auth-service
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth
      SPRING_DATASOURCE_USERNAME: auth
      SPRING_DATASOURCE_PASSWORD: auth
    depends_on:
      postgres-auth:
        condition: service_started
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    networks: [ats-net]

  refdata-service:
    build:
      context: ./platform/refdata-service
    ports:
      - "9011:9011"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    networks: [ats-net]

  swaps-service:
    build:
      context: ./platform/swaps-service
    ports:
      - "9021:9021"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-swaps:5432/swaps
      SPRING_DATASOURCE_USERNAME: swaps
      SPRING_DATASOURCE_PASSWORD: swaps
    depends_on:
      postgres-swaps:
        condition: service_started
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    networks: [ats-net]

  api-gateway:
    build:
      context: ./platform/api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    networks: [ats-net]
