version: "3.9"

networks:
  ats-net:

volumes:
  pgdata-auth:
  pgdata-swaps:

services:
  postgres-auth:
    image: postgres:16
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    networks:
      - ats-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-swaps:
    image: postgres:16
    environment:
      POSTGRES_USER: swaps
      POSTGRES_PASSWORD: swaps
      POSTGRES_DB: swaps
    ports:
      - "5434:5432"
    volumes:
      - pgdata-swaps:/var/lib/postgresql/data
    networks:
      - ats-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swaps"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build:
      context: .
      dockerfile: platform/config-server/Dockerfile
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ats-net
    restart: unless-stopped

  discovery-server:
    build:
      context: .
      dockerfile: platform/discovery-server/Dockerfile
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      config-server:
        condition: service_started
    networks:
      - ats-net
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "9555:9555"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth
      SPRING_DATASOURCE_USERNAME: auth
      SPRING_DATASOURCE_PASSWORD: auth
    depends_on:
      postgres-auth:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    networks:
      - ats-net
    restart: unless-stopped

  refdata-service:
    build:
      context: .
      dockerfile: services/refdata-service/Dockerfile
    ports:
      - "9011:9011"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    networks:
      - ats-net
    restart: unless-stopped

  swaps-service:
    build:
      context: .
      dockerfile: services/swaps-service/Dockerfile
    ports:
      - "9021:9021"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-swaps:5432/swaps
      SPRING_DATASOURCE_USERNAME: swaps
      SPRING_DATASOURCE_PASSWORD: swaps
    depends_on:
      postgres-swaps:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    networks:
      - ats-net
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: platform/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    networks:
      - ats-net
    restart: unless-stopped