server:
  port: 9003

spring:
  application:
    name: swaps-service

  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5433/swaps}"
    username: "${DB_USER:swaps}"
    password: "${DB_PASS:swaps}"
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_SERVER_URL:http://localhost:8761/eureka}"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: "never"

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: WARN
