server: { port: 9000 }
spring:
  application: { name: auth-service }
  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: auth
    password: auth
  jpa.hibernate.ddl-auto: validate
  flyway.enabled: true
eureka.client.service-url.defaultZone: http://localhost:8761/eureka
