services:
  discovery:
    image: ghcr.io/some/java21-empty:latest  # placeholder; usually run from IDE
    profiles: ["app"]  # won't start by default
  postgres-auth:
    image: postgres:16
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth -d auth"]
      interval: 5s
      timeout: 3s
      retries: 10

  postgres-swaps:
    image: postgres:16
    environment:
      POSTGRES_USER: swaps
      POSTGRES_PASSWORD: swaps
      POSTGRES_DB: swaps
    ports:
      - "5434:5432"
    volumes:
      - pgdata-swaps:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swaps -d swaps"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata-auth:
  pgdata-swaps:
