server: { port: 8888 }
spring:
  application: { name: config-server }
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mutwila-Alinta/ats-config-repo
          default-label: main
          username: ${GITHUB_USERNAME}      # anything valid on GitHub (your username)
          password: ${GITHUB_TOKEN}         # PAT with repo read
          clone-on-start: true              # optional: fail fast at startup
management.endpoints.web.exposure.include: health,info
